name: mati_byahe
description: "A new Flutter project for fair transport fares in Mati City using QR codes."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  supabase_flutter: ^2.6.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  pin_code_fields: ^8.0.1
  mailer: ^6.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
